### ISSUE TITLE
Let's start

### ISSUE THREAD

**Issue by Safronek** [Safronek/Study-Event#1]
Всім привіт. Пропоную почати роботу планування заходу. Пишіть будь ласка свої ідеї заходу і ми щось оберемо. Я пропоную провести дебати між школярами.

**Comment by DianaKuzmenko** [comment]
Привіт. А захід має бути більш рухливий та активний чи більше у форматі лекції?

**Comment by Safronek** [comment]
Може бути будь який, як собі придумаємо. Я пропоную щось активне, лекцій в школярів і так є достатньо.

**Comment by DianaKuzmenko** [comment]
Я спочатку подумала що було б круто розказати детально про когось з відомих особистостей. Можливо сучасних українців, які внесли якийсь вклад до збережння української історії або щось таке.

**Comment by DianaKuzmenko** [comment]
Можна було б зробити захід в такому форматі як The Ukraїnians. https://theukrainians.org/

І щось на таку тему, щоб донести важливість української культури
наприклад, як ця стаття: 
![image](https://user-images.githubusercontent.com/22542471/111297897-35f20280-865f-11eb-82d4-a1f0b473d482.png)

**Comment by Safronek** [comment]
Виглядає цікаво  🤔. 
Отже, тепер в нас є 2 теми для заходу.

**Comment by DianaKuzmenko** [comment]
Але все-таки думаю що спочатку варто провесати дебати! 
Ти маєш рацію в тому, що лекцій у них достатньо , а щось рухливе і захопливе вартувало б додати :)

**Comment by Safronek** [comment]
Тоді треба дочекатися ще думки інших наших колег і почати роботу над заходом.

**Comment by DianaKuzmenko** [comment]
Так, тоді поки чекаємо колег - створю нове issue яке нам вартувало б розглянути...

@bodik16 , @temirhanchik долучайтесь)

**Comment by Safronek** [comment]
Добре, з колегами зв'язалась через месенджер. Вони долучаться пізніше. А зараз час визначити завдання для виконання проекту.
