### ISSUE TITLE
Step-by-step implementation

### ISSUE THREAD

**Issue by DianaKuzmenko** [Safronek/Study-Event#2]
Любі колеги, тут нам вартувало б визначити як ми будемо реалізовувати нашу подію та які кроки нам потрібно зробити, щоб дебати були успішними !

**Comment by DianaKuzmenko** [comment]
Думаю, спочатку варто учням розказати що таке дебати, бо напевно не всі знають. Як думаєте, вартувало б це зробити у форматі лекції, чи можливо презентації?

**Comment by Safronek** [comment]
Думаю було б цікавіше в форматі короткої презентації з яскравими, наглядними картинками.

**Comment by DianaKuzmenko** [comment]
Я також так думаю.


- [x] Якщо ви не проти, я _накидаю презентацію,_ а потім **спільно** її обговоримо та можливо щось змінимо,  щоб зробити _якісно та цікаво_ :)

**Comment by Safronek** [comment]
Круто, в тебе гарні презентації. Учням сподобається)

**Comment by Safronek** [comment]
Також на дебатах нам знадобляться судді. Можемо зв'язатися з Федерацією дебатів України, можливо вони пришлють когось, хто допоможе нам судити.

**Comment by DianaKuzmenko** [comment]
Думаю наразі можемо закривати це issue. В разі необхідності і додаткових кроків відкриємо ще раз!
