### ISSUE TITLE
Придумати 10 тем для дебатів між учнями.

### ISSUE THREAD

**Issue by Safronek** [Safronek/Study-Event#3]
(Далі з командою виберемо один)

**Comment by Safronek** [comment]
Сюди пропоную ктдати ідеї теми для дебатів.

**Comment by Safronek** [comment]
"ЦП пропонує заборонити вируб українських лісів"

**Comment by Safronek** [comment]
ЦП пропонує вбивати усіх бродячих тварин у місті
ЦП забороняє вируб українських лісів
ЦП пропонує змінити освітню програму у ВНЗ (або як там по новому), щоб студенти обирали професію після 2 курсу, як у США

**Comment by bodik16** [comment]
ЦП шкодує про стрімкий розвиток ІТ сфери

**Comment by bodik16** [comment]
ЦП шкодує про популяризацію талант-шоу

**Comment by bodik16** [comment]
Ця палата шкодує про стрімкий розвиток штучного інтелекту та пропонує обмежити його використання.

**Comment by Safronek** [comment]
> Ця палата шкодує про стрімкий розвиток штучного інтелекту та пропонує обмежити його використання.

ЦІкава і актуальна тема. Пропоную обрати її.

**Comment by Temirhanchik** [comment]
"ЦП пропонує прибрати фемінітиви з української мови"
"ЦП шкодує про проведення спортивних змагань на офіційному рівні"

**Comment by Safronek** [comment]
Отже, ми обрали тему дебатів "Ця палата шкодує про стрімкий розвиток штучного інтелекту та пропонує обмежити його використання." Пропоную всі наші кінцеві рішення оформити як план заходу в однойменному файлі, який я вже створила в репозиторії.
