### ISSUE TITLE
Знаходимо суддів на дебати

### ISSUE THREAD

**Issue by Safronek** [Safronek/Study-Event#5]
Також на дебатах нам знадобляться судді. Можемо зв'язатися з Федерацією дебатів України, можливо вони пришлють когось, хто допоможе нам судити.

_Originally posted by @Safronek in https://github.com/Safronek/Study-Event/issues/2#issuecomment-800179351_

**Comment by DianaKuzmenko** [comment]
Думаю це дуже гарна ідея ! Було б дуже круто, якби в нас були "справжні" судді , і учні відчули атмосферу дебатів цілком :)

**Comment by Safronek** [comment]
Отже, з зв'язалася з ФДУ. В нас буде справжній суддя :))
