### ISSUE TITLE
Розібратися з правилами дебатів та свормувати окремий файлик з правилами.

### ISSUE THREAD

**Issue by Safronek** [Safronek/Study-Event#8]

**Comment by DianaKuzmenko** [comment]
@bodik16 , Можливо тобі це допоможе гарно сформувати правила . Тут є дев'ять основних концептів: http://www.living-democracy.com.ua/wp-content/uploads/2015/02/puzzle_colour_ALB.png

**Comment by DianaKuzmenko** [comment]
Виглядає, що файл вже створено і закинуто, тому закриваю issue.
